### ISSUE TITLE
Css assets path

### ISSUE THREAD

**Issue by luclucluc** [arnoson/kirby-vite-basic-kit#3]
Hi Arno,
Thanks for this nice work. I have notice a path issue that I haven't been able to solve.
After build, in the css file, the path to the font is replaced by /dist/assets/myfont.woff2 while the font file is copied in the same folder as the css file. The path should just be ./myfont.woff2.

**Comment by arnoson** [comment]
Hi, can you explain a bit more?
What you describe sounds like the expected behaviour (the orginal font is placed inside `src` and gets build into `dist/assets`.
If I build the `kirby-vite-basic-kit` font loading is working.

**Comment by luclucluc** [comment]
Here is what I get after build
- the font is copied here public/dist/assets/myFontFile.woff2
- the css file is generated here public/dist/assets/file.css
- inside file.css I have @font-face{ font-family: myFontName; src: url(/dist/assets/myFontFile.woff2) }
So 'myFontFile.woff2' and 'file.css' are inside the same folder but the url path is using /dist/assets/...
Don't you have the same?

**Comment by arnoson** [comment]
It is using an absolut path (starting with '/', so it doesn't matter if the files are inside the same directory or not. When you build this example kit (without changing anything) is the font (Compagnon-Bold.woff2) not loading?

**Comment by luclucluc** [comment]
My bad I get it. It's be because I did a test using www.mywebsite.com/public/. While 'public' should be the root folder 'www'.
Sorry about this and thanks for your time.

**Comment by arnoson** [comment]
Ah okay, glad you figured it out!
