### ISSUE TITLE
npm run preview

### ISSUE THREAD

**Issue by Messa1** [arnoson/kirby-vite-basic-kit#4]
Hi.

npm run preview - didn't work out of the box.

```
GET http://localhost:5173/@vite/client net::ERR_CONNECTION_REFUSED
GET http://localhost:5173/index.js net::ERR_CONNECTION_REFUSED
```

I think there are some config part's missing for that.
Maybe you have the best view over your files and can add that - or i will check vite and try to make a PR when I found it.

**Comment by Messa1** [comment]
I guess i found the problem - I have set up cache also for local dev and if i turn in kirby config to off it seem to work.
Thats a strange behave - but maybe that make sense 😄 

If i have in my kirby config cache to true i get the error if not it woks.

```
return [
  'debug' => true,
  'cache' => [
    'pages' => [
      'active' => true,
    ]
  ]
];
```

So i have remove out of my dev env and it works i leave the cache in prod env.

**Comment by arnoson** [comment]
Yeah you should never cache in development (and also make sure to clear the remote cache after uploading the files to your server).
